"""book publisher and category update

Revision ID: 88b04d2585ae
Revises: 713a166a2ae8
Create Date: 2024-09-18 09:45:26.431999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b04d2585ae'
down_revision: Union[str, None] = '713a166a2ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_publisher_key', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('book_publisher_key', 'book', ['publisher'])
    # ### end Alembic commands ###
