services:
  # FastAPI application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_api_app
    ports:
      - "6969:6969"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - pykron
    volumes:
      - .:/app
    command: make start_server
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: frontend_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cowrywise_frontend
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

  redis:
    image: redis:7.2.5-alpine
    container_name: frontend_redis
    ports:
      - "7329:6379"
    volumes:
      - redis_data:/data

  pykron:
    container_name: frontend_celery_worker

    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: make start_cron_job
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
