"""User, Book, abd Book Borrowed.

Revision ID: 6b6094cc5b40
Revises: 
Create Date: 2024-09-17 16:08:44.660874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6094cc5b40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_uid', sa.UUID(), nullable=False),
    sa.Column('admin_uid', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_borrowed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('date_created_utc', sa.DateTime(), nullable=True),
    sa.Column('date_updated_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('book_uid'),
    sa.UniqueConstraint('publisher')
    )
    op.create_index(op.f('ix_book_admin_uid'), 'book', ['admin_uid'], unique=False)
    op.create_table('user',
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date_created_utc', sa.DateTime(), nullable=True),
    sa.Column('date_updated_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('book_borrowed',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('book_uid', sa.UUID(), nullable=True),
    sa.Column('borrowed_by', sa.UUID(), nullable=True),
    sa.Column('date_borrowed', sa.Date(), nullable=True),
    sa.Column('duration_borrowed_for', sa.Integer(), nullable=True),
    sa.Column('date_created_utc', sa.DateTime(), nullable=True),
    sa.Column('date_updated_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['book.book_uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrowed_by'], ['user.user_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_borrowed')
    op.drop_table('user')
    op.drop_index(op.f('ix_book_admin_uid'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
